# Generated by Django 5.2 on 2025-04-08 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0003_empresaativausuario'),
        ('funcionarios', '0002_alter_funcionario_bairro_alter_funcionario_cbocargo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Absenteismo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_empresa', models.CharField(db_column='codigo_empresa', max_length=20)),
                ('MATRICULA_FUNC', models.CharField(blank=True, max_length=30, null=True)),
                ('NOME_FUNCIONARIO', models.CharField(blank=True, max_length=120, null=True)),
                ('UNIDADE', models.CharField(blank=True, max_length=130, null=True)),
                ('SETOR', models.CharField(blank=True, max_length=130, null=True)),
                ('DT_NASCIMENTO', models.DateField(blank=True, null=True)),
                ('SEXO', models.IntegerField(blank=True, choices=[(0, 'Não preenchido'), (1, 'Masculino'), (2, 'Feminino')], default=0, null=True)),
                ('TIPO_ATESTADO', models.IntegerField(choices=[(0, 'Atestado em dias'), (1, 'Declaração em horas')], default=0)),
                ('DT_INICIO_ATESTADO', models.DateField()),
                ('DT_FIM_ATESTADO', models.DateField()),
                ('HORA_INICIO_ATESTADO', models.CharField(blank=True, max_length=5, null=True)),
                ('HORA_FIM_ATESTADO', models.CharField(blank=True, max_length=5, null=True)),
                ('DIAS_AFASTADOS', models.IntegerField(blank=True, null=True)),
                ('HORAS_AFASTADO', models.CharField(blank=True, max_length=5, null=True)),
                ('CID_PRINCIPAL', models.CharField(blank=True, max_length=10, null=True)),
                ('DESCRICAO_CID', models.CharField(blank=True, max_length=264, null=True)),
                ('GRUPO_PATOLOGICO', models.CharField(blank=True, max_length=80, null=True)),
                ('TIPO_LICENCA', models.CharField(blank=True, max_length=100, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absenteismos', to='dashboard.empresa')),
                ('funcionario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='absenteismos', to='funcionarios.funcionario')),
            ],
            options={
                'verbose_name': 'Absenteísmo',
                'verbose_name_plural': 'Absenteísmos',
                'ordering': ['-DT_INICIO_ATESTADO'],
                'indexes': [models.Index(fields=['codigo_empresa'], name='absenteismo_codigo__8fa4de_idx'), models.Index(fields=['MATRICULA_FUNC'], name='absenteismo_MATRICU_35f73a_idx'), models.Index(fields=['funcionario'], name='absenteismo_funcion_3e88b0_idx'), models.Index(fields=['DT_INICIO_ATESTADO'], name='absenteismo_DT_INIC_5445d8_idx'), models.Index(fields=['DT_FIM_ATESTADO'], name='absenteismo_DT_FIM__90efb8_idx'), models.Index(fields=['CID_PRINCIPAL'], name='absenteismo_CID_PRI_feb3ec_idx')],
            },
        ),
    ]
