# Generated by Django 5.2 on 2025-04-08 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absenteismo', '0001_initial'),
        ('dashboard', '0003_empresaativausuario'),
        ('funcionarios', '0002_alter_funcionario_bairro_alter_funcionario_cbocargo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='absenteismo',
            name='funcionario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='absenteismos', to='funcionarios.funcionario'),
        ),
        migrations.AddIndex(
            model_name='absenteismo',
            index=models.Index(fields=['funcionario'], name='absenteismo_funcion_3e88b0_idx'),
        ),
    ]
