# Generated by Django 5.2 on 2025-04-14 07:24

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absenteismo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CNAE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('descricao', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='NTEP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('cids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, default=list, size=None)),
                ('cnae', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ntep', to='absenteismo.cnae')),
            ],
        ),
    ]
