# Generated by Django 5.2 on 2025-04-14 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('absenteismo', '0002_cnae_ntep'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cnae',
            table='cnae',
        ),
    ]
