# Generated by Django 5.2 on 2025-04-14 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('absenteismo', '0003_alter_cnae_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ntep',
            table='ntep',
        ),
    ]
