# Generated by Django 5.2 on 2025-04-14 07:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absenteismo', '0004_alter_ntep_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ntep',
            name='cids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='ntep',
            name='descricao',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
