# Generated by Django 5.2 on 2025-04-14 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absenteismo', '0005_alter_ntep_cids_alter_ntep_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cnae',
            name='codigo',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='cnae',
            name='descricao',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
