# Generated by Django 5.2 on 2025-04-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absenteismo', '0006_alter_cnae_codigo_alter_cnae_descricao'),
        ('dashboard', '0003_empresaativausuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='cnae',
            name='empresas',
            field=models.ManyToManyField(blank=True, related_name='cnaes', to='dashboard.empresa'),
        ),
    ]
