# Generated by Django 5.2 on 2025-04-06 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CODIGO', models.CharField(max_length=20, unique=True)),
                ('RAZAOSOCIAL', models.CharField(max_length=200)),
                ('ENDERECO', models.CharField(max_length=110)),
                ('NUMEROENDERECO', models.CharField(max_length=20)),
                ('COMPLEMENTOENDERECO', models.CharField(max_length=300)),
                ('BAIRRO', models.CharField(max_length=80)),
                ('CIDADE', models.CharField(max_length=50)),
                ('CEP', models.CharField(max_length=11)),
                ('UF', models.CharField(max_length=2)),
                ('CNPJ', models.CharField(max_length=20)),
                ('ATIVO', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_vinculo', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'empresa')},
            },
        ),
        migrations.AddField(
            model_name='empresa',
            name='usuarios',
            field=models.ManyToManyField(through='dashboard.UsuarioEmpresa', to=settings.AUTH_USER_MODEL),
        ),
    ]
