# Generated by Django 5.2 on 2025-04-16 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0003_empresaativausuario'),
        ('funcionarios', '0002_alter_funcionario_bairro_alter_funcionario_cbocargo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convocacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CODIGOEMPRESA', models.CharField(max_length=20)),
                ('NOMEABREVIADO', models.CharField(blank=True, max_length=100, null=True)),
                ('UNIDADE', models.CharField(blank=True, max_length=100, null=True)),
                ('CIDADE', models.CharField(blank=True, max_length=100, null=True)),
                ('ESTADO', models.CharField(blank=True, max_length=2, null=True)),
                ('BAIRRO', models.CharField(blank=True, max_length=100, null=True)),
                ('ENDERECO', models.CharField(blank=True, max_length=200, null=True)),
                ('CEP', models.CharField(blank=True, max_length=10, null=True)),
                ('CNPJUNIDADE', models.CharField(blank=True, max_length=20, null=True)),
                ('SETOR', models.CharField(blank=True, max_length=100, null=True)),
                ('CARGO', models.CharField(blank=True, max_length=100, null=True)),
                ('CODIGOFUNCIONARIO', models.CharField(max_length=20)),
                ('CPFFUNCIONARIO', models.CharField(blank=True, max_length=20, null=True)),
                ('MATRICULA', models.CharField(blank=True, max_length=30, null=True)),
                ('DATAADMISSAO', models.DateField(blank=True, null=True)),
                ('NOME', models.CharField(blank=True, max_length=120, null=True)),
                ('EMAILFUNCIONARIO', models.CharField(blank=True, max_length=100, null=True)),
                ('TELEFONEFUNCIONARIO', models.CharField(blank=True, max_length=20, null=True)),
                ('CODIGOEXAME', models.CharField(blank=True, max_length=20, null=True)),
                ('EXAME', models.CharField(blank=True, max_length=100, null=True)),
                ('ULTIMOPEDIDO', models.DateField(blank=True, null=True)),
                ('DATARESULTADO', models.DateField(blank=True, null=True)),
                ('PERIODICIDADE', models.IntegerField(blank=True, null=True)),
                ('REFAZER', models.DateField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convocacoes', to='dashboard.empresa')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convocacoes', to='funcionarios.funcionario')),
            ],
            options={
                'unique_together': {('CODIGOFUNCIONARIO', 'CODIGOEXAME')},
            },
        ),
    ]
