# Generated by Django 5.2 on 2025-04-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convocacao',
            name='CODIGOEXAME',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
