# Generated by Django 5.2 on 2025-04-16 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocacao', '0002_alter_convocacao_codigoexame'),
        ('funcionarios', '0002_alter_funcionario_bairro_alter_funcionario_cbocargo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convocacao',
            name='CODIGOEXAME',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='convocacao',
            name='CODIGOFUNCIONARIO',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='convocacao',
            name='MATRICULA',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='convocacao',
            name='funcionario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='convocacoes', to='funcionarios.funcionario'),
        ),
    ]
